// ─── index.js ────────────────────────────────────────────────────────────────
// Homepage runtime. Previously this file's logic was tightly coupled to a
// hand-authored DOM — it expected IDs like #heroBgImg, #eventsGrid,
// #storeHoursTime, #exploreTrail to be statically present.
//
// In the sections refactor those IDs are now generated by js/sections.js at
// runtime when the page's sections[] array is fetched and rendered into
// <main id="sections"></main>. The existing helpers (applySiteInfo,
// renderLinks, renderHoursCards, renderEvents, updateStoreStatus, and the
// scroll-trail animation) are kept exactly as before — we just render the
// sections FIRST so the DOM they query against exists.
// ─────────────────────────────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', function () {
  // Set footer year immediately (footer markup is static in index.html)
  var yearEl = document.getElementById('footerYear');
  if (yearEl) yearEl.textContent = new Date().getFullYear();

  // Kick off the async boot (fetches settings + events + page sections,
  // renders them, then wires up all the existing behavior).
  initSite();

  // Refresh the open/closed pill every minute
  setInterval(updateStoreStatus, 60000);
});

// ─── Fallback data (used if APIs are unavailable) ────────────────────────────
var DAYS = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
var siteSettings = {
  storeHours:    DAYS.map(function(d)   { return { day:d, open:'08:30', close:'19:30', closed:false }; }),
  snackbarHours: DAYS.map(function(d,i) { return { day:d, open:i<6?'09:00':null, close:i<6?'15:00':null, closed:i===6 }; }),
};
var sectionsData = null; // Populated by loadAndRenderSections()

// ─── Time helpers ────────────────────────────────────────────────────────────
function toMins(t) { if (!t) return null; var p = t.split(':').map(Number); return p[0]*60 + p[1]; }
function fmt12(t) {
  if (!t) return '\u2014';
  var p = t.split(':').map(Number);
  var ampm = p[0] < 12 ? 'AM' : 'PM';
  var h12  = p[0] % 12 || 12;
  return h12 + ':' + String(p[1]).padStart(2,'0') + ' ' + ampm;
}

function todayHours(hoursArr) {
  var jsDay = new Date().getDay();
  var idx   = jsDay === 0 ? 6 : jsDay - 1;
  return hoursArr[idx] || null;
}

function hoursVary(hoursArr) {
  var open = hoursArr.filter(function (h) { return !h.closed; });
  if (!open.length) return false;
  var first = open[0].open + '|' + open[0].close;
  return open.some(function (h) { return (h.open + '|' + h.close) !== first; });
}

function summarizeDays(hoursArr) {
  var open   = hoursArr.filter(function (h) { return !h.closed; });
  var closed = hoursArr.filter(function (h) { return  h.closed; });
  if (!closed.length) return 'Open Every Day';
  if (closed.length === 1) return 'Closed ' + closed[0].day;
  var openDays = open.map(function (h) { return h.day; });
  if (!openDays.length) return 'Closed Every Day';
  return openDays[0] + ' \u2013 ' + openDays[openDays.length - 1];
}

function renderHoursCard(hoursArr, timeId, daysId, scheduleId) {
  var timeEl  = document.getElementById(timeId);
  var daysEl  = document.getElementById(daysId);
  var schedEl = document.getElementById(scheduleId);
  if (!timeEl || !daysEl || !schedEl) return; // Card not on the page
  var open = hoursArr.filter(function (h) { return !h.closed; });

  if (!open.length) {
    timeEl.textContent = 'Closed'; daysEl.textContent = 'All Days';
    timeEl.style.display = ''; daysEl.style.display = '';
    schedEl.style.display = 'none';
    return;
  }

  if (hoursVary(hoursArr)) {
    timeEl.style.display = 'none'; daysEl.style.display = 'none';
    schedEl.style.display = '';
    var now = new Date();
    var todayIdx = now.getDay() === 0 ? 6 : now.getDay() - 1;
    schedEl.innerHTML = hoursArr.map(function (h, i) {
      var timeStr = h.closed ? 'Closed' : (fmt12(h.open) + ' \u2013 ' + fmt12(h.close));
      var classes = [
        i === todayIdx ? 'is-today' : '',
        h.closed ? 'is-closed' : '',
      ].filter(Boolean).join(' ');
      return '<div class="hours-schedule-row' + (classes ? ' ' + classes : '') + '">'
           +   '<span class="hours-schedule-day">'  + h.day  + '</span>'
           +   '<span class="hours-schedule-time">' + timeStr + '</span>'
           + '</div>';
    }).join('');
  } else {
    timeEl.textContent = fmt12(open[0].open) + ' \u2013 ' + fmt12(open[0].close);
    daysEl.textContent = summarizeDays(hoursArr);
    timeEl.style.display = ''; daysEl.style.display = '';
    schedEl.style.display = 'none';
  }
}

// ─── Update store open/closed pill ───────────────────────────────────────────
function updateStoreStatus() {
  var today = todayHours(siteSettings.storeHours);
  var el    = document.getElementById('storeStatus');
  if (!el) return;
  if (!today || today.closed || !today.open) {
    el.textContent = 'Closed Today';
    el.className   = 'store-status is-closed';
    return;
  }
  var now     = new Date();
  var current = now.getHours() * 60 + now.getMinutes();
  var opens   = toMins(today.open);
  var closes  = toMins(today.close);
  var text, state;
  if (current >= opens && current < closes) {
    text = 'Open Now'; state = 'is-open';
  } else if (current < opens) {
    text = 'Opens ' + fmt12(today.open); state = 'is-closed';
  } else {
    text = 'Opens ' + fmt12(today.open) + ' Tomorrow'; state = 'is-closed';
  }
  el.textContent = text;
  el.className   = 'store-status ' + state;
}

// ─── Render quick-links (hero panel + nav overlay + footer) ─────────────────
function renderLinks(links) {
  var ql = (links && links.length) ? links : DEFAULT_LINKS;

  // 1. Hero quick-links panel (only if the Hero section was rendered)
  var heroPanel = document.getElementById('heroLinksPanel');
  if (heroPanel) {
    // Keep the header, drop any previously-rendered links
    heroPanel.querySelectorAll('.hv2-link').forEach(function (el) { el.remove(); });
    ql.forEach(function (lk) {
      var isExt = lk.url && lk.url.indexOf('http') === 0;
      var a = document.createElement('a');
      a.href = lk.url;
      a.className = 'hv2-link';
      if (isExt) { a.target = '_blank'; a.rel = 'noopener noreferrer'; }
      a.innerHTML = getLinkIcon(lk.icon) + '<span>' + escNavHtml(lk.text) + '</span><span class="hv2-arr">&rarr;</span>';
      heroPanel.appendChild(a);
    });
  }

  // 2. Nav overlay (defined in nav.js)
  renderNavLinks(ql);

  // 3. Footer quick links
  var footerEl = document.getElementById('footerQuickLinks');
  if (footerEl) {
    footerEl.innerHTML = ql.map(function (lk) {
      var isExt  = lk.url && lk.url.indexOf('http') === 0;
      var target = isExt ? ' target="_blank" rel="noopener noreferrer"' : '';
      return '<a href="' + escNavHtml(lk.url) + '" class="gf-link"' + target + '>'
           + getLinkIcon(lk.icon) + escNavHtml(lk.text) + '</a>';
    }).join('');
  }
}

// ─── Render hours cards ──────────────────────────────────────────────────────
function renderHoursCards() {
  renderHoursCard(siteSettings.storeHours,    'storeHoursTime',          'storeHoursDays',          'storeHoursSchedule');
  renderHoursCard(siteSettings.snackbarHours, 'snackbarHoursTime',       'snackbarHoursDays',       'snackbarHoursSchedule');
  // Footer copies (always present — footer is static HTML)
  renderHoursCard(siteSettings.storeHours,    'footerStoreHoursTime',    'footerStoreHoursDays',    'footerStoreHoursSchedule');
  renderHoursCard(siteSettings.snackbarHours, 'footerSnackbarHoursTime', 'footerSnackbarHoursDays', 'footerSnackbarHoursSchedule');
}

// ─── Apply site-info fields from settings ────────────────────────────────────
function applySiteInfo(s) {
  if (!s) return;
  if (s.phone) {
    var digits        = s.phone.replace(/\D/g, '');
    var callBtn       = document.getElementById('callBtn');
    var callBtnPhone  = document.getElementById('callBtnPhone');
    var footerPhone   = document.getElementById('footerPhone');
    if (callBtn)      { callBtn.href = 'tel:' + digits; }
    if (callBtnPhone) { callBtnPhone.textContent = s.phone; }
    if (footerPhone)  { footerPhone.textContent = s.phone; }
  }
  // heroDescription / heroButtonText / heroButtonLink / heroBgPhoto are now
  // owned by the Hero section's data. They are still mirrored into settings
  // (for backward compat + rollback) but sections.js reads them during render
  // so this block is intentionally empty in the new flow.

  // Mirror phone into the hero "Call Us" quick-link if that pattern is in use
  if (s.phone) {
    var el = document.getElementById('heroCallLink');
    if (el) el.href = 'tel:' + s.phone.replace(/\D/g, '');
  }
}

// ─── Load and render page sections ───────────────────────────────────────────
// Fetches /api/pages/home then hands the sections[] to js/sections.js.
// Returns a promise so the caller knows when DOM queries become valid.
function loadAndRenderSections(settings, events) {
  var mount = document.getElementById('sections');
  if (!mount) return Promise.resolve();

  return fetch('/api/pages/home')
    .then(function (r) { return r.ok ? r.json() : null; })
    .catch(function () { return null; })
    .then(function (data) {
      var sections = (data && Array.isArray(data.sections))
        ? data.sections
        : (window.SECTIONS ? window.SECTIONS.defaultHomepageSections() : []);

      sectionsData = { sections: sections };

      if (!window.SECTIONS) {
        // sections.js failed to load — render nothing, keep the page valid
        console.warn('SECTIONS module not loaded; homepage will be empty.');
        return;
      }

      window.SECTIONS.renderSectionList(sections, mount, { settings: settings, events: events });
    });
}

// ─── Load settings + events + sections from API ──────────────────────────────
function initSite() {
  // Render quick-links with defaults immediately so the nav overlay isn't blank
  renderLinks(null);

  Promise.all([
    fetch('/api/settings').then(function (r) { return r.ok ? r.json() : null; }).catch(function () { return null; }),
    fetch('/api/events').then(function (r) { return r.ok ? r.json() : null; }).catch(function () { return null; }),
  ]).then(function (results) {
    var sData = results[0];
    var eData = results[1];

    if (sData) {
      // sData.deliHours is the KV field name — copy to snackbarHours for local use
      siteSettings = Object.assign({}, sData, { snackbarHours: sData.deliHours });
    }

    // Render sections FIRST — every downstream helper queries IDs that only
    // exist after render (heroLinksPanel, eventsGrid, storeHoursTime, etc.)
    return loadAndRenderSections(siteSettings, eData && eData.events ? eData.events : []).then(function () {
      applySiteInfo(siteSettings);
      renderLinks(siteSettings.quickLinks || null);
      renderHoursCards();
      updateStoreStatus();

      if (eData && eData.events) {
        renderEvents(eData.events);
      }

      // Scroll-driven trail animation must initialize AFTER sections render
      initExploreTrail();
    });
  }).then(revealPage).catch(revealPage);
}

// Page-load fade-in: remove .page-loading, add .page-loaded so base.css
// transitions opacity 0 → 1. Called unconditionally (even on init error)
// so the user always sees *something*.
function revealPage() {
  document.body.classList.remove('page-loading');
  document.body.classList.add('page-loaded');
}

// ─── Render events into the Events section's grid ────────────────────────────
function renderEvents(events) {
  if (!events || !events.length) return; // section stays hidden
  var grid    = document.getElementById('eventsGrid');
  var section = document.getElementById('events');
  if (!grid || !section) return;

  grid.innerHTML = events.map(function (ev, idx) {
    var dateStr = ev.date
      ? new Date(ev.date + 'T12:00:00').toLocaleDateString('en-US', { weekday:'long', month:'long', day:'numeric', year:'numeric' })
      : '';
    var imgHtml = ev.photo
      ? '<img class="event-img" src="/images/' + ev.photo + '" alt="' + escHtml(ev.title) + '" loading="lazy"/>'
      : '<div class="event-img-placeholder">\u2726</div>';
    var ctaHtml = (ev.ctaText && ev.ctaLink)
      ? '<a class="event-cta-btn" href="' + escHtml(ev.ctaLink) + '" target="_blank" rel="noopener noreferrer">' + escHtml(ev.ctaText) + ' \u2192</a>'
      : '';
    var body = '<div class="event-body topo-light">'
             +   (dateStr ? '<div class="event-date">' + dateStr + '</div>' : '')
             +   '<div class="event-title">' + escHtml(ev.title) + '</div>'
             +   (ev.description ? '<div class="event-desc">' + escHtml(ev.description) + '</div>' : '')
             +   ctaHtml
             + '</div>';
    if (idx === 0) {
      return '<div class="event-card event-card--featured">' + body + imgHtml + '</div>';
    }
    return '<div class="event-card event-card--standard">' + imgHtml + body + '</div>';
  }).join('');
  section.style.display = '';
}

function escHtml(s) {
  return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

// ─── Exploring Esmeralda — scroll-driven trail animation ─────────────────────
// (Previously an IIFE with its own DOMContentLoaded listener; that timing
// doesn't work anymore because the Explore section is built later. We now
// call initExploreTrail() after sections render.)
var exploreTrailInited = false;
function initExploreTrail() {
  var trail = document.getElementById('exploreTrail');
  var fill  = document.getElementById('trailFill');
  var stops = document.querySelectorAll('.explore-stop');
  if (!trail || !fill || !stops.length) return;

  var ticking = false;

  function getProgress() {
    var rect  = trail.getBoundingClientRect();
    var viewH = window.innerHeight;
    var start = viewH * 0.8;
    var total = rect.height + start;
    var done  = start - rect.top;
    return Math.max(0, Math.min(1, done / total));
  }

  function update() {
    ticking = false;
    fill.style.height = (getProgress() * 100) + '%';
    stops.forEach(function (stop) {
      var sr = stop.getBoundingClientRect();
      if (sr.top < window.innerHeight * 0.68) {
        stop.classList.add('is-active');
      }
    });
  }

  function onScroll() {
    if (!ticking) {
      ticking = true;
      requestAnimationFrame(update);
    }
  }

  // Only attach the scroll listener once across page lifecycles
  if (!exploreTrailInited) {
    window.addEventListener('scroll', onScroll, { passive: true });
    exploreTrailInited = true;
  }
  update(); // run once after render so any already-visible stops activate
}
